language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      dist: trusty
      env: TOXENV=py36
      sudo: false
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env: TOXENV=py37
      sudo: true

install:
    - pip install -e ".[dev]"

script:
    - tox

after_success:
  - tox -e coveralls